language: java
before_install:
  - git submodule update --init --recursive
install:
  - true
  - gradle :fucJars
  - gradle :jbJars
  - gradle :jbJars
script: gradle :crosstest:test
notifications:
  email:
    on_success: never
    on_failure: never
